spring:
  datasource:
    url: jdbc:postgresql://dpg-crhfhuaj1k6c73e18uug-a.singapore-postgres.render.com:5432/study_sync
    username: study_sync_user
    password: BLDsOWdtjI5pgESvQN3NC3d1U7CFF1FO
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: off

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 2592000000 # 30 days
      #      expiration: 86400000 # a day
      refresh-token:
        expiration: 2592000000 # 30 days
server:
  servlet:
    context-path: /api

logging:
  level:
    root: warn
